---
###############################
# Switch language to Japanese #
###############################

# Prerequisite: Japanese language pack was installed
- name: Test if language pack ja is installed
  win_shell: |
      DISM.exe /Online /Get-Intl /English |
      Select-String -SimpleMatch 'Installed language(s)'|
      ForEach-Object { if($_ -match 'ja-JP'){ $Matches[0] }}
  register: lang_installed
  failed_when: lang_installed.stdout | length == 0
  tags: langpack

- name: Set Languagelist
  win_shell: Set-WinUserLanguageList -LanguageList ja-JP,en-US -Force
  tags: langpack

- name: Overwrite UI language
  win_shell: Set-WinUILanguageOverride -Language ja-JP
  tags: langpack

- name: Region Setting
  win_region:
    copy_settings: "true"
    format: ja-JP
    unicode_language: ja-JP
  register: result
  tags: langpack

- name: Change Region - Reboot
  win_reboot:
  when: result.restart_required
  tags: langpack
