---
##########
# gcc_64 #
##########
- name: Check if gcc-6.4 is installed
  shell: /usr/bin/gcc-6.4 >/dev/null 2>&1
  ignore_errors: yes
  register: gcc_installed
  tags: gcc-6.4

# gcc
- name: Download gcc-6.4.0 source
  get_url:
    url: http://gnu.mirror.globo.tech/gcc/gcc-6.4.0/gcc-6.4.0.tar.gz
    dest: '/tmp/gcc-6.4.0.tar.gz'
    force: no
    mode: 0755
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

- name: Extract gcc
  unarchive:
    src: /tmp/gcc-6.4.0.tar.gz
    dest: /tmp/
    copy: False
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

- name: Running configure, compile and install for gcc-6.4.0
  shell: cd /tmp/gcc-6.4.0 && ./contrib/download_prerequisites && ./configure --prefix=/opt/gcc-6.4.0 --disable-multilib && make -j {{ ansible_processor_vcpus }} && make install
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

# Create symlinks
- name: Create symlink for gcc-6.4
  file:
    src: /opt/gcc-6.4.0/bin/gcc
    dest: /usr/bin/gcc-6.4
    owner: root
    group: root
    state: link
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

- name: Create symlink for g++-6.4
  file:
    src: /opt/gcc-6.4.0/bin/g++
    dest: /usr/bin/g++-6.4
    owner: root
    group: root
    state: link
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

- name: Create symlink for c++-6.4
  file:
    src: /opt/gcc-6.4.0/bin/c++
    dest: /usr/bin/c++-6.4
    owner: root
    group: root
    state: link
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

- name: Create symlink for libstdc++.so.6.0.22
  file:
    src: /opt/gcc-6.4.0/lib64/libstdc++.so.6.0.22
    dest: /usr/lib/libstdc++.so.6.0.22
    owner: root
    group: root
    state: link
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4

- name: Create symlink for libstdc++.so.6
  file:
    src: /usr/lib64/libstdc++.so.6.0.22
    dest: /usr/lib/libstdc++.so.6
    owner: root
    group: root
    state: link
    force: true
  when:
    - gcc_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: gcc-6.4
