---
################################
# Visual Studio Community 2019 #
################################

- name: Test if VS 2019 is installed
  win_stat:
    path: 'C:\Program Files (x86)\Microsoft Visual Studio\2019'
  register: vs2019_installed
  tags: MSVS_2019

- name: Download Visual Studio Community 2019
  win_get_url:
    url: 'https://ci.adoptopenjdk.net/userContent/winansible/MSVS_installers/vs_community19.exe'
    dest: 'C:\temp\vs_community19.exe'
    force: no
    checksum: 57a346bc1f6a3d9018057aa275f7a9e9b78307fce28b220ba50ef3c2fbc4127f
    checksum_algorithm: sha256
  when: (not vs2019_installed.stat.exists)
  tags: MSVS_2019

- name: Install Visual Studio Community 2019
  win_shell: 'C:\temp\vs_community19.exe --wait --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended;includeOptional --quiet --norestart'
  args:
    executable: cmd
  when: (not vs2019_installed.stat.exists)
  register: vs2019_error
  failed_when: vs2019_error.rc != 0 and vs2019_error.rc != 3010
  tags: MSVS_2019

- name: Register Visual Studio Community 2019 DIA SDK shared libraries
  win_command: 'regsvr32 /s "{{ item }}"'
  with_items:
    - C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\msdia140.dll
    - C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\amd64\msdia140.dll
  tags: MSVS_2019

- name: Reboot machine after Visual Studio installation
  win_reboot:
    reboot_timeout: 1800
    shutdown_timeout: 1800
  when: (not vs2019_installed.stat.exists)
  tags: MSVS_2019
