---
################################
# Visual Studio Community 2019 #
################################

- name: Test if VS 2019 is installed
  win_stat:
    path: 'C:\Program Files (x86)\Microsoft Visual Studio\2019'
  register: vs2019_installed
  tags: MSVS_2019

- name: Download Visual Studio Community 2019
  win_get_url:
    url: 'https://aka.ms/vs/16/release/vs_community.exe'
    dest: 'C:\temp\vs_community19.exe'
    force: no
    checksum: 03f1768299410a2c359f61c88abbe038c5bcfd51d71854cf6437e633ebdefa06
    checksum_algorithm: sha256
  when: (not vs2019_installed.stat.exists)
  tags: MSVS_2019

- name: Install Visual Studio Community 2019
  win_shell: 'C:\temp\vs_community19.exe --wait --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended;includeOptional --quiet --norestart'
  args:
    executable: cmd
  when: (not vs2019_installed.stat.exists)
  register: vs2019_error
  failed_when: vs2019_error.rc != 1 and vs2019_error.rc != 0
  tags: MSVS_2019

- name: Register Visual Studio Community 2019 DIA SDK shared libraries
  win_command: 'regsvr32 /s "{{ item }}"'
  with_items:
    - C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\msdia140.dll
    - C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\amd64\msdia140.dll
  tags: MSVS_2019

- name: Reboot machine after Visual Studio installation
  win_reboot:
    reboot_timeout: 1800
    shutdown_timeout: 1800
  when: (not vs2019_installed.stat.exists)
  tags: MSVS_2019
