---
#############
# Swap_File #
#############
- name: Set Swapfile path /swapfile
  set_fact:
    swap_path: /swapfile
  when:
    - (ansible_distribution_major_version != "9" and ansible_architecture != "armv7l")
  tags: swap_file

- name: Set Swapfile path /tmp/swapfile on BeagleBone
  set_fact:
    swap_path: /tmp/swapfile
  when:
    - (ansible_distribution_major_version == "9" and ansible_architecture == "armv7l")
  tags: swap_file

- name: Check if Swapfile already exists
  stat:
    path: "{{ swap_path }}"
  register: swap_exists
  tags: swap_file

- debug: var=swap_path
  tags: swap_file

- name: Create swap file
  command: "fallocate -l 2G {{ swap_path }}"
  when:
    - swap_exists.stat.exists == false
    - (ansible_distribution != "SLES" and ansible_distribution_major_version != "11") or (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7" )
  tags: swap_file

- name: Create swap file - via DD on SLES 11 and CentOS 7
  command: dd if=/dev/zero of=/swapfile bs=250M count=8
  when:
    - swap_exists.stat.exists == false
    - (ansible_distribution == "SLES" and ansible_distribution_major_version == "11") or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" )
  tags: swap_file

- name: Set swap file permissions
  file: path="{{ swap_path }}"
        owner=root
        group=root
        mode=0600
  when:
    - swap_exists.stat.exists == false
  tags: swap_file

- name: Create swap area device
  command: "mkswap {{ swap_path }}"
  when:
    - swap_exists.stat.exists == false
  tags: swap_file

- name: Mount swap file
  command: "swapon {{ swap_path }}"
  when:
    - swap_exists.stat.exists == false
  tags: swap_file

- name: Add swap to fstab
  mount: src="{{ swap_path }}"
    name=none
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present
  when:
    - swap_exists.stat.exists == false
  tags: swap_file
