---
language: python
python: "2.7"

sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Install Linter
  - ./travis-ci-linter/install_lint.sh

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Check AdoptOpenJDK_Unix_Playbook syntax.
- cd ansible && ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --syntax-check
