---
language: python
python: "2.7"

sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Check AdoptOpenJDK_Unix_Playbook syntax.
- cd ansible && ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --syntax-check
