---
arch:
  - arm64-graviton2
  - ppc64le

env:
  - TARGET="adoptopenjdk/centos7_build_image"

os:
  - linux

dist: bionic

virt: lxd
group: edge
install: skip

script:
  - docker build -t $TARGET:$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH -f ansible/Dockerfile.CentOS7 .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push $TARGET:$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH; fi