---
###########
# Java 13 #
###########
- name: Test if Java13 is already installed
  win_stat:
    path: 'C:\openjdk\jdk-13\bin'
  register: java13_installed
  tags: Java13

- name: Check if Java13 is already downloaded
  win_stat:
    path: 'C:\temp\jdk-13.zip'
  register: java13_download
  tags: Java13

- name: Download Java13
  win_get_url:
    url: https://api.adoptopenjdk.net/v2/binary/releases/openjdk13?openjdk_impl={{ bootjdk }}&os=windows&arch=x64&release=latest&type=jdk&heap_size={{ heapsize }}
    dest: 'C:\temp\jdk-13.zip'
  when: (java13_download.stat.exists == false) and (java13_installed.stat.exists == false)
  tags: Java13

- name: Install Java13
  win_unzip:
    src: C:\temp\jdk-13.zip
    dest: C:\Program Files\Java
  when: (java13_installed.stat.exists == false)
  tags: Java13

- name: Create symlink to directory without spaces if not already there
  win_shell: for /D %a in ("C:\Program Files\Java\jdk-13*") do IF NOT EXIST "C:\openjdk\jdk-13" MKLINK /D "C:\openjdk\jdk-13" "%a"
  args:
    executable: cmd.exe
    creates: 'C:\openjdk\jdk-13'
  tags: Java13
