---
################
# Jenkins user #
################
- name: Create Jenkins user
  win_user:
    name: "{{ Jenkins_Username }}"
    fullname: AdoptOpenJDK Jenkins User
    password: "{{ lookup('file', '{{ Jenkins_Win_Passwd }}') }}"
    state: present
    password_never_expires: yes
    groups:
      - Users, Remote Desktop Users
  tags: jenkins_user
