####################################################
# Uninstall conflicting packages from base image   #
# if they were installed via rpm unless yum exists #
####################################################
- name: Confirm yum is installed - /usr/bin/yum
  stat:
    path: /usr/bin/yum
  register: yum
  tags: yum

- name: Uninstall conflicting packages
  shell: rpm -e --nodeps $(rpm -qa | grep -E "cloud-init|perl|openssl") 2>/dev/null
  ignore_errors: True
  when: yum.stat.islnk is not defined
  tags:
    - rpm_remove
    - yum
    # TODO: rpm used in place of yum or rpm_key module
    - skip_ansible_lint

####################################
# Install yum and update to latest #
####################################
- name: Download yum.sh
  get_url:
    url: ftp://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/ezinstall/ppc/yum.sh
    validate_certs: False
    dest: /tmp/
    mode: 0775
    timeout: 25
  when: yum.stat.islnk is not defined
  tags: yum

- name: Install yum and dependencies
  command: /tmp/yum.sh
  register: result.yum
  ignore_errors: yes
  when: yum.stat.islnk is not defined
  tags:
    - yum
    #TODO: Package installs should not use latest
    - skip_ansible_lint

- name: Yum update
  yum:
    update_cache: yes
    name: '*'
    state: latest
  tags:
    - yum
    #TODO: Package installs should not use latest
    - skip_ansible_lint

- name: Install yum package support
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - autoconf
    - bc
    - bison
    - coreutils
    - cpio
    - cups-devel
    - cups-libs
    - cmake
    - expect
    - flex
    - freetype2-devel
    - fontconfig-devel
    - gawk
    - git
    - grep
    - libXrender-devel
    - libffi-devel
    - libiconv
    - libunistring
    - make
    - m4
    - pcre
    - perl
    - pkg-config
    - popt
    - sed
    - tar
    - tcl
    - tk
    - unzip
    - wget
    - xz-libs
    - zip
    - zsh
  tags: yum
