---
########################################
# AdoptOpenJDK - Ansible Playbook for: #
# --------------- AIX ---------------  #
########################################

- hosts: all
  remote_user: root
  become: yes
  environment:
    PATH: "/opt/IBM/xlC/13.1.3/bin:/opt/freeware/bin:{{ ansible_env.PATH }}"
    PERL_MB_OPT: "--install_base /opt/freeware"
    PERL_MM_OPT: "INSTALL_BASE=/opt/freeware"
  vars:
    swap_size: 4096

  tasks:
    - block:
        # Set standard variables
        - name: Load AdoptOpenJDKs variable file
          include_vars: ../adoptopenjdk_variables.yml
        # Install bash if it's not already there
        - name: Check if bash is installed
          shell: bash --version >/dev/null 2>&1
          register: does_bash_exist
          ignore_errors: yes
        - name: install bash
          yum: name=bash state=present update_cache=yes
          when: does_bash_exist.rc != 0

  roles:
    - filesystem
    - ramdisk
    - openssl
    - yum
    - java7
    - java8
    - java9
    - java10
    - java11
    - java12
    - X11
    - XLC13
    - XLC16
    - ant
    - ant-contrib
    - syslog
    - login-shell
    - jenkins
    - freemarker
    - nagios
    - superuser
    - ntp
    - sendmail
    - fullcore
    - swap

   handlers:
    - name: restart machine
      shell: echo 'shutdown -r now "Triggered by Ansible updates."' | at now + 1 minutes
      async: 1
      poll: 0
      failed_when: False