###############
#     ant     #
###############
- name: Checking for Ant availability
  stat:
    path: /usr/bin/ant
  register: ant
  tags: ant

- debug:
    msg: "Ant installed, skipping download and installation"
  when: ant.stat.islnk is defined
  tags: ant

- name: Download and extract ant
  unarchive:
    src: https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.9-bin.zip
    dest: /opt
    remote_src: yes
  when: ant.stat.islnk is not defined
  tags: ant

- name: Create symlink for ant
  file: src=/opt/apache-ant-1.9.9/bin/ant dest=/usr/bin/ant state=link
  when: ant.stat.islnk is not defined
  tags: ant

###############
# ant-contrib #
###############
- name: Checking for ant-contrib availability
  stat:
    path: /opt/apache-ant-1.9.9/lib/ant-contrib.jar
  register: antcontrib
  tags: ant-contrib

- debug:
    msg: "ant-contrib.jar installed, skipping download"
  when: antcontrib.stat.exists == True
  tags: ant-contrib

- name: Download and extract ant-contrib
  unarchive:
    src: https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-1.0b2/a
    dest: /tmp/
    remote_src: yes
  when: antcontrib.stat.exists == False
  tags: ant-contrib

- name: Move ant-contrib.jar to lib folder
  command: mv /tmp/ant-contrib/lib/ant-contrib.jar /opt/apache-ant-1.9.9/lib/
  when: antcontrib.stat.exists == False
  tags: ant-contrib

- name: Clean ant-contrib tmp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/ant-contrib
    - /tmp/ant-contrib-1.0b2-bin.tar.gz
  tags: ant-contrib
