---
##############
# Shortnames #
##############

# Ensures that directories have alternative shortnames for the builds

- name: Check if shortName.ps1 has been downloaded
  win_stat:
    path: C:\temp\shortName.ps1
  register: script_download
  tags:
    - shortnames

- name: Download shortName.ps1
  win_get_url:
    url: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-infrastructure/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/scripts/shortName.ps1
    dest: C:\temp\shortName.ps1
  when: (not script_download.stat.exists)
  tags:
    - shortnames

- name: Enable shortnames on drive C:/
  win_shell: fsutil 8dot3name set C: 0
  tags:
    - shortnames

- name: Run shortname script against Vars list
  win_shell: C:\temp\shortName.ps1 "{{ item.name }}" "{{ item.shortname }}"
  with_items:
    - { name: "Microsoft Visual Studio", shortname: "MIB055~1" }
    - { name: "Microsoft Visual Studio 9.0" , shortname: "MICROS~2.0" }
    - { name: "Microsoft Visual Studio 10.0" , shortname: "MICROS~3.0" }
    - { name: "Microsoft Visual Studio 11.0" , shortname: "MICROS~4.0" }
    - { name: "Microsoft Visual Studio 12.0" , shortname: "MICROS~1.0" }
    - { name: "Microsoft Visual Studio 14.0" , shortname: "MI0E91~1.0" }
    - { name: "Windows Kits" , sname: "WINDOW~4" }
  tags:
    - shortnames
