#########################################################################
# Install X11 extensions                                                #
# x11.base.lib installp download requiring an IBMid                     #
# https://www.ibm.com/support/pages/fileset-information-x11baselib      #
# x11.adt.ext installp download requiring an IBMid                      #
# https://www.ibm.com/support/pages/fileset-information-x11adtext       #
# x11.vfb installp download requiring an IBMid                          #
# https://www.ibm.com/support/pages/fileset-information-x11vfb          #
#########################################################################
---
# Rather than run lslpp - use stat on the lpp directories
# /usr/lpp/X11.base/X11.base.lib      X11.base.lib
# /usr/lpp/X11/include/X11/extensions X11.adt.ext
# /usr/lpp/X11.vfb                    X11.vfb
- name: Verify X11 software
  block:
  - name: Verify X11 base library
    stat:
      path: /usr/lpp/X11.base/X11.base.lib
    register: _base
  - name: Verify X11 extensions requirements
    stat:
      path: /usr/lpp/X11/include/X11/extensions
    register: _ext
  - name: Verify X11 Frame Buffer Requirements
    stat:
      path: /usr/lpp/X11.vfb
    register: _vfb
  - name: Verify Readiness #1
    set_fact:
      _x11rdy: "{{ _base.stat.exists
        and _ext.stat.exists
        and _vfb.stat.exists }}"
  tags: x11

- name: Install from Vendor Files
  block:
    - name: Ensure destination for Vendor Files exists
      file:
        state: directory
        path: /tmp/x11

    - name: Unpack Vendor Files
      unarchive:
        src: /Vendor_Files/aix/OpenGL_X11.tar
        dest: /tmp/x11
        remote_src: no
      ignore_errors: yes
      register: _vendor_copied

    - name: Install IBM X11 Extensions - installp
      command:
        installp -e /tmp/x11.log -aXYgd /tmp/x11 X11.adt.ext X11.vfb X11.base.lib
      register: _installp
      ignore_errors: yes
      when: _vendor_copied.failed is defined and _vendor_copied.failed != true

    - name: Remove X11 install files
      file:
        state: absent
        path: /tmp/x11

    - name: Re-Verify X11 base requirements
      stat:
        path: /usr/lpp/X11.base/X11.base.lib
      register: _base

    - name: Verify X11 extensions requirements
      stat:
        path: /usr/lpp/X11/include/X11/extensions
      register: _ext

    - name: Verify X11 Frame Buffer Requirements
      stat:
        path: /usr/lpp/X11.vfb
      register: _vfb
    - name: Set X11 Readiness
      set_fact:
        _x11rdy: "{{ _base.stat.exists
          and _ext.stat.exists
          and _vfb.stat.exists }}"
  when: _x11rdy == false
  tags: [x11, vendor_files]

- name: Report X11 Readiness
  debug:
    msg: "All required X11 components are installed: {{ _x11rdy }}"
  tags: x11
