############
# IBM XL C #
############
- name: Checking for XLC availability
  stat:
    path: /usr/bin/xlc
  register: xlc
  tags: xlc

  - debug:
      msg: "xlc installed, skipping download and installation"
    when: xlc.stat.islnk is defined
    tags: xlc

- name: Transfer and Extract XLC
  unarchive:
    src: /Vendor_Files/aix/IBM_XL_C_C___FOR_AIX_V13.1.3_EMG.tar.gz
    dest: /tmp
    remote_src: no
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: Install IBM XL C - installp
  command: installp -aXYgd /tmp/usr/sys/inst.images all
  register: result.xlc
  ignore_errors: yes
  when: xlc.stat.islnk is not defined
  tags: xlc

- debug: msg='Erorrs from the previous installp command normal'
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: TestIBM XL C
  command: /opt/IBM/xlC/13.1.3/bin/xlc -qversion
  register: xlc_qversion
  tags: xlc

- name: Display XL C qversion information
  debug:
    msg: "{{ xlc_qversion.stdout }}"
  tags: xlc

- name: Symlink - /usr/bin/xlc
  file: src=/opt/IBM/xlC/13.1.3/bin/xlc dest=/usr/bin/xlc state=link
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: Symlink - /usr/bin/xlc++
  file: src=/opt/IBM/xlC/13.1.3/bin/xlc++ dest=/usr/bin/xlc++ state=link
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: Symlink - /usr/bin/xlC
  file: src=/opt/IBM/xlC/13.1.3/bin/xlC dest=/usr/bin/xlC state=link
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: Symlink - /usr/bin/xlc_r
  file: src=/opt/IBM/xlC/13.1.3/bin/xlc_r dest=/usr/bin/xlc_r state=link
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: Symlink - /usr/bin/xlC_r
  file: src=/opt/IBM/xlC/13.1.3/bin/xlc_r dest=/usr/bin/xlC_r state=link
  when: xlc.stat.islnk is not defined
  tags: xlc

- name: Symlink - /usr/bin/gxlC
  file: src=/opt/IBM/xlC/13.1.3/bin/gxlC dest=/usr/bin/gxlC state=link
  when: xlc.stat.islnk is not defined
  tags: xlc
