##############
# freemarker #
##############
- name: Check for freemarker.jar existence
  stat:
    path: /home/{{ Jenkins_Username }}/freemarker.jar
  register: freemarker
  tags: freemarker

- debug:
    msg: "freemarker.jar found, skipping download"
  when: freemarker.stat.exists == True
  tags: freemarker

- name: Download and extract freemarker.jar
  unarchive:
    src: https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/freemarker-2.3.
    dest: /tmp/
    remote_src: yes
    owner: "{{ Jenkins_Username }}"
    group: staff
    mode: 0755
  when: freemarker.stat.exists == False
  tags: freemarker

- name: Move freemarker.jar to /home/{{ Jenkins_Username }} folder
  command: mv /tmp/freemarker-2.3.8/lib/freemarker.jar /home/{{ Jenkins_Username }}
  when: freemarker.stat.exists == False
  tags: freemarker

- name: Clean freemarker tmp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/freemarker-2.3.8
    - /tmp/freemarker-2.3.8.tar.gz
  tags: freemarker
