---
########################
# Include OS variables #
########################
- name: Include OS variables
  include_vars: "../vars/main.yml"
  tags: main

##########
# cygwin #
##########
- name: Test if Cygwin is already installed
  win_stat:
    path: 'C:\cygwin64'
  register: cygwin_installed
  tags: cygwin

- name: Retrieve cygwin cache from ci.adoptopenjdk.net
  win_get_url:
    url: https://ci.adoptopenjdk.net/userContent/winansible/cygwin64.tar.xz
    dest: C:/temp/cygwin64.tar.xz
    checksum: e89608178b4d99042fd356687c84aa18e220fb0dcd0c9d4bc60983ce538d9efe
    checksum_algorithm: sha256
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Retrieve cygwin toolset from ci.adoptopenjdk.net
  win_get_url:
    url: https://ci.adoptopenjdk.net/userContent/winansible/cygwin64/bin/*zip*/bin.zip
    dest: C:/temp/cyg_toolset.zip
    checksum: 5974b93eefe033bd57cc14c30f7ba67584a5b9249b71cede7d9e05d87113d908
    checksum_algorithm: sha256
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Extract cygwin_toolset to C:/temp
  win_shell: |
    cd C:\temp
    C:\7-Zip\7z.exe x C:\temp\cyg_toolset.zip
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Use cygwin 'tar' to extract cygwin cache
  win_shell: |
    $env:path="C:\temp\bin;$env:Path"
    cd C:\
    tar --force-local -xvf C:\temp\cygwin64.tar.xz
  args:
    executable: powershell
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Change git config to not replace Line endings
  win_shell: "C:/cygwin64/bin/git config --system core.autocrlf false"
  tags: cygwin

- name: Remove c:\cygwin64\bin from the path if it exists
  win_path:
    name: PATH
    elements:
      - 'C:\cygwin64\bin'
    scope: machine
    state: absent
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

# NOTE: This construct is because an SQL Server entry is being added to
# the path which has an erroneous quote in it which causes problems for SETX
# See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1401
- name: Remove speech mark from the %PATH%
  win_shell: 'setx /M PATH "%PATH:\"=%"'
  args:
    executable: cmd
  when: (not cygwin_installed.stat.exists)
  tags:
    - cygwin

- name: Add c:\cygwin64\bin to front of %PATH%
  win_shell: 'setx /M PATH "C:\cygwin64\bin;%PATH%"'
  args:
    executable: cmd
  when: (not cygwin_installed.stat.exists)
  tags:
    - cygwin

- name: Reboot machine for PATH changes to take effect
  win_reboot:
    reboot_timeout: 1800
  when: (not cygwin_installed.stat.exists)
  tags: cygwin
