---
####################
# Custom Make-3.82 #
####################
- name: Test if Make-3.82 is already installed
  win_stat:
    path: 'C:\openjdk\make-3.82'
  register: make-3.82_installed
  tags: Make-3.82

- name: Download make-3.82
  win_get_url:
    url: 'https://ci.adoptopenjdk.net/userContent/make-3.82.zip'
    dest: 'C:\temp\make-3.82.zip'
  when: (make-3.82_installed.stat.exists == false)
  tags: Make-3.82

- name: Extract make-3.82 to C:\openjdk\
  win_unzip:
    src: 'C:\temp\make-3.82.zip'
    dest: 'C:\openjdk\'
  when: (make-3.82_installed.stat.exists == false)
  tags: Make-3.82

- name: Configure make-3.82
  raw: bash /cygdrive/c/openjdk/make-3.82/configure
  when: (make-3.82_installed.stat.exists == false)
  tags: Make-3.82

- name: Make make-3.82
  raw: make -C /cygdrive/c/openjdk/make-3.82/
  when: (make-3.82_installed.stat.exists == false)
  tags: Make-3.82
