---
############################
# Build_Packages_and_tools #
############################
- name: Install Build Tool Packages
  package: "name={{ item }} state=latest"
  with_items: "{{ Build_Tool_Packages }}"
  tags: build_tools

- name: Create symlink for gmake to make
  file:
    src: /usr/bin/make
    dest: /usr/bin/gmake
    owner: root
    group: root
    state: link
  tags: build_tools

- name: Install Test Tool Packages
  package: "name={{ item }} state=latest"
  with_items: "{{ Test_Tool_Packages }}"
  tags: test_tools
