###################################
# AdoptOpenJDK - Ansible Playbook #
###################################
- hosts: "{{ groups['Vendor_groups'] | default('build:test:!*zos*:!*win*:!*macos*:!*aix*') }}"
  gather_facts: yes
  tasks:

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Nagios_Plugins
    - Nagios_Master_Config
    - Nagios_Tunnel

