---
###################
# AdoptOpenJDK 10 #
###################
- name: Check if jdk10 is already installed in the target location
  shell: ls -ld /usr/lib/jvm/jdk-10+* >/dev/null 2>&1
  ignore_errors: yes
  register: adoptopenjdk10_installed
  tags: adoptopenjdk10

- name: Install latest release if one not already installed
  unarchive:
    src: https://api.adoptopenjdk.net/openjdk10/nightly/x64_linux/latest/binary
    dest: /usr/lib/jvm
    remote_src: yes
  when:
    - ansible_architecture == "x86_64"
  tags: adoptopenjdk10

- name: Install latest release if one not already installed
  unarchive:
    src: https://api.adoptopenjdk.net/openjdk10/nightly/{{ ansible_architecture }}_linux/latest/binary
    dest: /usr/lib/jvm
    remote_src: yes
  when:
    - ansible_architecture != "x86_64"
    - ansible_architecture != "armv7l"
  tags: adoptopenjdk10
