---
############
# Security #
############
- name: Ensure 'no-agent-forwarding' doesn't exist in root's authorized_key file
  lineinfile:
    path: /root/.ssh/authorized_key
    state: absent
    regexp: '^no-agent-forwarding'
  when:
    - Superuser_Account == "Enabled"
  tags: security
  
- name: Ensure keybox's ssh key is applied to root's authorized_key file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ Keybox_SSHKey }}') }}"
  when:
    - Superuser_Account == "Enabled"
  tags: security
  
- name: Ensure security settings are applied to sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: " {{ item }} "
  with_items:
    - PermitRootLogin without-password
    - PasswordAuthentication no
    - ChallengeResponseAuthentication no
  when:
    - Superuser_Account == "Enabled"
  tags: security

- name: Restart ssh service
  service:
    name: ssh
    state: restarted
    enabled: yes
  when:
    - Superuser_Account == "Enabled"
  tags: security
