##############
# IBM Java 7 #
##############
- name: Check for Java7 availability
  stat:
    path: /usr/java7
  register: java7
  tags: java7

- debug:
    msg: "Java7 found, skipping download and installation"
  when: java7.stat.isdir is defined
  tags: java7

- name: Transfer and Extract Java7
  unarchive:
    src: /Vendor_Files/aix/openjdk-7u-aix.tar
    dest: /tmp
    remote_src: no
  when: java7.stat.isdir is not defined
  tags: java7

- name: Move extracted Java7 to /usr/java7
  command: mv /tmp/j2sdk-image /usr/java7
  when: java7.stat.isdir is not defined
  tags: java7

- name: Test Java7
  command: /usr/java7/bin/java -version
  register: java7_version
  tags: java7

- name: Display Java7 version information
  debug:
    msg: "{{ java7_version.stderr }}"
  tags: java7
