---
######################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on macOS on x86 hardware #
######################################################################################

###########################################################################
# License Information:                                                    #
# Nagios core and its plugins are lincesed under GPL                      #
# For more information please see: https://www.nagios.com/legal/licenses/ #
###########################################################################

########################################
# Install Nagios dependencies packages #
########################################
- name: Install additional packages used by Nagios
  package: "name={{ item }} state=latest"
  with_items:
    - nagios-plugins
  tags: [nagios_plugins, adoptopenjdk]
