---
##########
# ZULU-7 #
##########

# Install zulu-7 for OSs that don't have openjdk-7 available in their package manager:
#  CentOS/RHEL 8, Debian 10, Ubuntu1804, openSUSE/SLES 12 (only tested for x86_64)

- name: Check if Zulu-7 is already installed in the target location
  shell: ls -ld /usr/lib/jvm/zulu7 2>&1
  ignore_errors: yes
  register: zulu7_installed
  when:
    - ansible_os_family != "Darwin"
    - ansible_architecture == "x86_64"
    - ((ansible_distribution == "Redhat" or ansible_distribution == "CentOS") and (ansible_distribution_major_version|int >= "8")) or
      ((ansible_distribution == "SLES" or ansible_distribution == "openSUSE") and (ansible_distribution_major_version|int >= "12")) or
      (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= "18") or
      (ansible_distributiob == "Debian" and ansible_distribution_major_version|int >= "10")
  tags: zulu7

  # See here for reason to skip_ansible_lint: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1325#issuecomment-627374329
- name: Install latest release if not already installed
  shell: mkdir -p /usr/lib/jvm/zulu7 && wget https://cdn.azul.com/zulu/bin/zulu7.38.0.11-ca-jdk7.0.262-linux_x64.tar.gz  -O - | tar xzf - -C /usr/lib/jvm/zulu7 --strip-components=1
  when:
    - ansible_os_family != "Darwin"
    - ansible_architecture == "x86_64"
    - ((ansible_distribution == "Redhat" or ansible_distribution == "CentOS") and (ansible_distribution_major_version|int >= "8")) or
      ((ansible_distribution == "SLES" or ansible_distribution == "openSUSE") and (ansible_distribution_major_version|int >= "12")) or
      (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= "18") or
      (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= "10")
  tags:
    - skip_ansible_lint
    - zulu7
