
#################################################
# Build basic test images for each distribution #
#################################################

- name: Fetch Dockerfiles : NOTE : NEED TO TRANSLATE arch=aarch64
  copy:
    src: ../Dockerfiles
    dest: /tmp/Dockerfiles

- name: Collate all Dockerfile names
  find:
    paths: "/tmp/Dockerfiles/"
    patterns: "Dockerfile.*"
  register: dockerfiles

 - name: Translate architecture name in dockerfiles
   replace: dest={{items}} regexp="enabled=1" replace="enabled=0"
   with_items: {{ dockerfiles }}

- name: Create docker images for each distribution for test
  command: docker build --cpu-period=100000 --cpu-quota=800000 -t aqa_{{ item }} --memory=8G -f /tmp/Dockerfile.{{ item }} .
  with_items: u1604 u1804 u2004 u2010 cent8 f33

##############################################################
# Start the containers                                       #
# If startallcontainers is skipped, only start three of them #
##############################################################

- name: Start Ubuntu 16.04 container
  command: docker run -p 2222:22 --cpus=2.0 --memory=6G --detach --name U1604_2222 aqa_u1604
  tags: startcontainers

- name: Start Ubuntu 18.04 container
  command: docker run -p 2223:22 --cpus=4.0 --memory=6G --detach --name U1804_2223 aqa_u1804
  tags: startcontainers, startallcontainers

- name: Start Ubuntu 20.04 container
  command: docker run -p 2224:22 --cpus=2.0 --memory=6G --detach --name U2004_2224 aqa_u2004
  tags: startcontainers

- name: Start Ubuntu 20.10 container
  command: docker run -p 2225:22 --cpus=4.0 --memory=6G --detach --name U2010_2225 aqa_u2010
  tags: startcontainers, startallcontainers

- name: Start fedora 33 container
  command: docker run -p 2227:22 --cpus=2.0 --memory=6G --detach --name   f33.2227 aqa_f33  
  tags: startcontainers
