---
##################################################
# AdoptOpenJDK - Prereqs for running git-hg jobs #
##################################################
- name: Install packages for java and git
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - openjdk-8-jre-headless
    - mercurial
    - git
- name: Create /usr/local/bin
  file: path=/usr/local/bin state=directory
- name: Download git-remote-hg
  get_url:
    url: https://raw.github.com/felipec/git-remote-hg/master/git-remote-hg
    dest: /usr/local/bin/git-remote-hg
    mode: 0555
- name: Install prereqs needed for git-hg jobs
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - zlib1g-dev
    - libcurl4-openssl-dev
    - gettext
- name: Install prereqs needed for other jobs which will runon the machine (jtreg, jemmy, jtharness)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - unzip
    - zip
    - ant
