---
####################
# LLVM/Clang 64bit #
####################
# Clang 64bit is an OpenJ9 prerequisite.

- name: Test if Clang 64bit is already installed (required by OpenJ9)
  win_stat:
    path: 'C:\Program Files\LLVM\bin\clang.exe'
  register: clang_64bit_installed
  tags: clang_64bit

- name: Download Clang 64bit
  win_get_url:
    url: https://releases.llvm.org/7.0.0/LLVM-7.0.0-win64.exe
    dest: 'C:\temp\'
    force: no
  when: clang_64bit_installed.stat.exists == false
  tags: clang_64bit

- name: Install Clang 64bit
  win_command: 'c:\temp\LLVM-7.0.0-win64.exe'
  when: clang_64bit_installed.stat.exists == false
  tags: clang_64bit

- name: Cleanup Clang 64bit installer
  win_file:
    path: 'c:\temp\LLVM-7.0.0-win64.exe'
    state: absent
  ignore_errors: yes
  tags: clang_64bit
