---
##########
# CentOS #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  # - alsa-lib-devel
  - autoconf
  - bind-utils
  - bzip2
  - cpio
  # - cups-devel
  - elfutils-libelf-devel
  # - fontconfig-devel
  # - freetype-devel
  - gcc
  - gcc-c++
  - glibc
  - glibc-common
  - glibc-devel
  - gmp-devel
  - java-1.7.0-openjdk-devel
  - java-1.8.0-openjdk-devel
  - libcurl-devel
  # - libpng-devel
  - lbzip2
  - make
  # - mesa-libGL-devel
  - mpfr-devel
  - ntp
  - openssl-devel
  - perl-CPAN
  - perl-DBI
  - perl-devel
  - perl-GD
  - perl-libwww-perl
  - perl-Time-HiRes
  - systemtap-sdt-devel
  - unzip
  - wget
  - xz
  - zip

# Additional_Build_Tools_CentOS7:
#   - libstdc++-static

# Additional_Build_Tools_x86_64:
#   - zulu-9

crontab_Patching: "/usr/bin/yum -y update"
