---
##########
# macOS #
##########

# Command Build Tool Packages

Build_Tool_Packages:
  - autoconf
  - coreutils
  - gnu-tar
  - wget

Build_Tool_Casks:
  - adoptopenjdk8
  - adoptopenjdk11

Test_Tool_Packages:
  - mercurial
  - pulseaudio
  - cpanminus
  - p7zip

Test_Tool_Casks:
  - xquartz
