---
###############
# WiX Toolset #
###############
- name: Test if WiX is already installed
  win_stat:
    path: 'C:\Program Files (x86)\WiX Toolset v3.14\bin\wix.dll'
  register: wix_installed
  tags: Wix

- name: Download WiX
  win_get_url:
    url: https://wixtoolset.org/downloads/v3.14.0.3910/wix314.exe
    dest: 'C:\temp\wix.exe'
    follow_redirects: all
    checksum: f333d4cf132f03b75222aa107633d28ce5ba8d612892b38cfc2ddc4cd92ad6de
    checksum_algorithm: sha256
  when: (not wix_installed.stat.exists)
  tags: Wix

- name: Install WiX
  win_package:
    path: 'C:\temp\wix.exe'
    product_id: WiX
    arguments: /S
  when: (not wix_installed.stat.exists)
  tags: Wix

- name: Cleanup WiX
  win_file:
    path: 'C:\temp\wix.exe'
    state: absent
  ignore_errors: yes
  tags: Wix

- name: Test if Windows 10 SDK is already installed
  win_stat:
    path: 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe'
  register: win10_sdk_installed
  tags: Wix

- name: Install windows-sdk-10.0 version 10.1.17763.1
  win_chocolatey:
    name: windows-sdk-10.1
    version: '10.1.17763.1'
  when: (not win10_sdk_installed.stat.exists)
  tags: Wix
