---
###############
# WiX Toolset #
###############
- name: Test if WiX is already installed
  win_stat:
    path: 'C:\Program Files (x86)\WiX Toolset v3.11\bin\wix.dll'
  register: wix_installed
  tags: Wix

- name: Install wixtoolset version 3.11.1
  win_chocolatey:
    name: wixtoolset
    version: '3.11.1'
  when: (not wix_installed.stat.exists)
  tags: Wix

- name: Test if Windows 10 SDK is already installed
  win_stat:
    path: 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe'
  register: win10_sdk_installed
  tags: Wix

- name: Install windows-sdk-10.0 version 10.1.17763.1
  win_chocolatey:
    name: windows-sdk-10.1
    version: '10.1.17763.1'
  when: (not win10_sdk_installed.stat.exists)
  tags: Wix