name: Docker

on:
  pull_request:
    paths:
    - ansible/**
    - .github/**
    branches:         
    - master
    - .github/**
  push:
    paths:
    - ansible/**
    branches:         
    - master


jobs:
  build-and-push-centos6:
    name: Centos6
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Docker Build & Push Centos6 Image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./ansible/Dockerfile.CentOS6
        repository: adoptopenjdk/centos6_build_image
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}

  build-and-push-centos7:
    name: Centos7
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Docker Build & Push Centos7 Image to Docker Hub
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/ppc64le\
          --output "type=image,push=false" \
          --file ./ansible/Dockerfile.CentOS7 .

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Buildx (push)
      if: github.ref == 'refs/heads/master'
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le \
          --output "type=image,push=true" \
          --tag adoptopenjdk/centos7_build_image:latest \
          --file ./ansible/Dockerfile.CentOS7 .

  build-and-push-alpine3:
    name: Alpine3
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Docker Build & Push Alpine3 Image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./ansible/Dockerfile.Alpine3
        repository: adoptopenjdk/alpine3_build_image
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}
