name: Vagrant Playbook Checker

on:
  pull_request:
    paths:
    - .github/workflows/build_vagrant_win.yml
    - ansible/playbooks/AdoptOpenJDK_Windows_Playbook/**
    branches:         
    - master

jobs:
  win2016:
    name: Windows 2016
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install ansible
        brew install --cask virtualbox vagrant
        vagrant plugin install vagrant-disksize

    - name: Setup Vagrant VM
      run: |
        cd ansible
        ln -sf Vagrantfile.Win2016 Vagrantfile
        vagrant up
        vagrantPORT=$(vagrant port | grep host | awk '{ print $4 }')
        rm -f playbooks/AdoptOpenJDK_Windows_Playbook/hosts.unx
        echo "[127.0.0.1]:${vagrantPORT}" >> playbooks/AdoptOpenJDK_Windows_Playbook/hosts.unx
        sed -i -e "s/.*hosts:.*/- hosts: all/g" playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
        # Uncomments and sets the ansible_password to 'vagrant', in adoptopenjdk_variables.yml
        sed -i'' -e "s/.*ansible_password.*/ansible_password: vagrant/g" playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml
        # If "credssp" isn't found in adoptopenjdk_variables.yml
        if ! grep -q "credssp" playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml;
        then
          # Add the "ansible_winrm_transport" to adoptopenjdk_variables.yml
          echo -e "\nansible_winrm_transport: credssp" >> playbooks/AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml
        fi

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i playbooks/AdoptOpenJDK_Windows_Playbook/hosts.unx -u vagrant -b --skip-tags adoptopenjdk playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
