name: Docker

on:
  pull_request:
    paths:
    - ansible/**
    branches:         
    - master
  push:
    paths:
    - ansible/**
    branches:         
    - master


jobs:
  build-and-push-centos6:
    name: Centos6
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Docker Build & Push Centos6 Image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./ansible/Dockerfile.CentOS6
        repository: adoptopenjdk/centos6_build_image
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}

  build-and-push-alpine3:
    name: Alpine3
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Docker Build & Push Alpine3 Image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./ansible/Dockerfile.Alpine3
        repository: adoptopenjdk/alpine3_build_image
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}

  build-and-push-windows2019:
    name: Windows 2019
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v2

    - name: Docker Build & Push Windows 2019 Base Image to Docker Hub
      run: |
        docker build -t adoptopenjdk/windows2019_build_image_base -f ansible/Dockerfile.windows2019_Base .

    - name: Docker Build & Push Windows 2019 VS2017 Image to Docker Hub
      run: |
        docker build -t adoptopenjdk/windows2019_build_image_vs2017 -f ansible/Dockerfile.windows2019_VS2017 .

    - name: Docker Build & Push Windows 2019 VS2013 Image to Docker Hub
      run: |
        docker build -t adoptopenjdk/windows2019_build_image_vs2013 -f ansible/Dockerfile.windows2019_VS2013 .
